#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

run_timesanitycheck() {
   trap "error_handler" ERR

   ## There is an exception in /etc/sudoers.d/timesanitycheck.
   sudo service timesanitycheck restart
}

check_bootclockrandomization() {
   trap "error_handler" ERR

   ## There is an exception in /etc/sudoers.d/bootclockrandomization.
   local exit_code
   exit_code="0"
   sudo service bootclockrandomization status >/dev/null 2>&1 || { exit_code="$?" ; true; };

   if [ "$exit_code" = "0" ]; then
      local MSG="<p>bootclockrandomization success.</p>"
      if [ "$verbose" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
      fi
   else
      local MSG
      MSG="<p><b>bootclockrandomization failed.</b> Please report this bug!</p>
<p>Last 6 lines of /var/log/bootclockrandomization.log:
<blockquote>$(tail -n 6 /var/log/bootclockrandomization.log)</blockquote></p>" || true
      $output ${output_opts[@]} --messagex --typex "error" --titlex "$TITLE" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "error" --titlecli "$TITLE" --message "$MSG"
   fi
}

check_timesanitycheck() {
   trap "error_handler" ERR

   ## There is an exception in /etc/sudoers.d/timesanitycheck.
   local exit_code
   exit_code="0"
   sudo service timesanitycheck status >/dev/null 2>&1 || { exit_code="$?" ; true; };

   ## When autostarted...
   if [ "$AUTOSTARTED" = "1" ]; then
      ## exit_code 2 means, that timesanitycheck has neither created a success nor a fail file (yet).
      if [ "$exit_code" = "2" ]; then
         local MSG="<p>It may have happened, that sdwdate was run before timesanitycheck.
<br></br>Let us wait a few seconds and try checking timesanitycheck status again.</p>"
         if [ "$verbose" = "1" ]; then
            $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"
            $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
         fi
         sleep "10" &
         lastpid="$!"
         wait "$lastpid"
         ## There is an exception in /etc/sudoers.d/timesanitycheck.
         local exit_code
         exit_code="0"
         sudo service timesanitycheck status >/dev/null 2>&1 || { exit_code="$?" ; true; };
      fi
   fi

   if [ "$exit_code" = "0" ]; then
      local MSG="<p>timesanitycheck success.</p>"
      if [ "$verbose" = "1" ]; then
         $output ${output_opts[@]} --messagex --typex "info" --titlex "$TITLE" --message "$MSG"
         $output ${output_opts[@]} --messagecli --typecli "info" --titlecli "$TITLE" --message "$MSG"
      fi
   else
      local MSG="<p><b>Time Sanity Check failed before running Network Time Synchronization (timesync)!!!</b> (code: $exit_code)</p>
<p>Last 6 lines of /var/log/timesanitycheck.log:
<blockquote>$(tail -n 6 /var/log/timesanitycheck.log)</blockquote>

Is your host clock slow or fast? If so, please power off, fix your host clock and restart.
<br></br>If your host clock is sane, please report a bug.</p>"
      $output ${output_opts[@]} --messagex --typex "error" --titlex "$TITLE" --message "$MSG"
      $output ${output_opts[@]} --messagecli --typecli "error" --titlecli "$TITLE" --message "$MSG"
   fi
}
