#!/bin/bash

parse_cmd() {
   trap "error_handler" ERR

   ## Thanks to:
   ## http://mywiki.wooledge.org/BashFAQ/035

   while :
   do
       case $1 in
           -v | --verbose)
               echo "$SCRIPTNAME verbose output..."
               echo "Script running as $(whoami)"
               verbose="1"
               shift
               ;;
           -f | --mode)
               MODE="$2"
               shift 2
               ;;
           --)
               shift
               break
               ;;
           -*)
               echo "$SCRIPTNAME unknown option: $1" >&2
               EXIT_CODE="1"
               cleanup "1"
               return 0
               ;;
           *)
               break
               ;;
       esac
   done

   ## If there are input files (for example) that follow the options, they
   ## will remain in the "$@" positional parameters.
}
