#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

output_func() {
   trap "error_handler" ERR

   if [ "$output_func_verbose" = "true" ]; then
      echo "Running: bash -x $output_tool --identifier $IDENTIFIER --whoami $who_ami ${1+$@}"
      bash -x $output_tool --identifier "$IDENTIFIER" --whoami "$who_ami" ${1+"$@"}
   else
      $output_tool --identifier "$IDENTIFIER" --whoami "$who_ami" ${1+"$@"}
   fi
   return "$?"
}

preparation() {
   trap "error_handler" ERR

   if [ -f "/var/run/sdwdate/timesync.pid" ]; then
      local oldpid
      oldpid="$(cat "/var/run/sdwdate/timesync.pid")" || true
      if [ ! "$oldpid" = "" ]; then
         ## $lastpid is used by by process_killer_helper.
         lastpid="$oldpid"
         process_killer_helper
         unset lastpid
      fi
   fi

   ## TODO
   #echo "$$" > "/var/run/sdwdate/timesync.pid"

   sync

   if [ "$display" = "" ]; then
      if [ "$DISPLAY" = "" ]; then
         display=":0"
      else
         display="$DISPLAY"
      fi
   fi

   local my_tty
   local my_tty_exit_code
   my_tty_exit_code="0"
   my_tty="$(tty)" || { my_tty_exit_code="$?" ; true; };

   if [ ! "$my_tty_exit_code" = "0" ]; then
      my_tty="none"
   fi

   ## Just in case.
   if [ "$my_tty" = "" ]; then
      my_tty="none"
   fi

   if [ "$DAEMON" = "1" ]; then
      true
   elif [ "$AUTOSTARTED" = "1" ]; then
      true
   else
      manualrun="1"
   fi

   TITLE="timesync - Monitor and user interface for sdwdate, bootclockrandomization and timesanitycheck"

   output_tool="/usr/lib/msgcollector/msgcollector"
   output="output_func"

   ## When run by sdwdate, --whoami has already been passed.
   ## When run by running timesync, auto detect own user name.
   if [ "$who_ami" = "" ]; then
      who_ami="$(whoami)" || who_ami="user"
   fi

   local id_exit_code="0"
   id -u "$who_ami" >/dev/null 2>&1 || { id_exit_code="$?" ; true; };

   if [ ! "$id_exit_code" = "0" ]; then
      echo "$BASH_SOURCE $FUNCNAME: Notification user (variable who_ami) is set to $who_ami, but that user does not exist. Exiting."
      exit 0
   fi

   $output --icon "$ICON"
   $output --parenttty "$my_tty"
   $output --whoami "$who_ami"
   $output --titlex "$TITLE"
   $output --titlecli "$TITLE"

   TIME_START="$(date +%s)"
}
