#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#set -x
set -o pipefail

ICON="/usr/share/icons/anon-icon-pack/timesync.ico"

SCRIPTNAME="$(basename $0)"
IDENTIFIER="timesync"

tmp="$(mktemp)"
progressbaridx="${tmp##*.}"
progressbaridx_main="$progressbaridx"

source /usr/lib/msgcollector/error_handler
trap "error_handler" ERR

timesync_source_list="\
check_clock
check_sdwdate
cleanup
parse_cmd
preparation
process_killer_helper
run_sdwdate
"

for i in $timesync_source_list; do
   if [ -f "$i" ]; then
      ## If the last character is a ~, ignore that file,
      ## because it was created by some editor,
      ## which creates backup files.
      if [ "${i: -1}" = "~" ]; then
         continue
      fi
      ## Skipping files such as .dpkg-old and .dpkg-dist.
      if ( echo "$i" | grep -q ".dpkg-" ); then
         true "skip $i"
         continue
      fi
      source "$i"
   fi
done

timesync_post_error() {
   trap "error_handler" ERR

   preparation

   ## no $output --forget

   local MSG="${1+"$@"}"

   if [ "$MSG" = "" ]; then
      local MSG="$FUNCNAME: empty error message. Please report this bug!"
   fi

   $output ${output_opts[@]} --messagex --typex "error" --titlex "$TITLE" --message "$MSG"
   $output ${output_opts[@]} --messagecli --typecli "error" --titlecli "$TITLE" --message "$MSG"

   cleanup
}

timesync_post_error ${1+"$@"}
